services:
  pocketbase:
    build: .
    container_name: thermometer-pocketbase
    restart: always
    environment:
      TZ: Europe/Prague
    ports:
      - "8090:8090"
    volumes:
      - ./data:/pb_data
      - ./public:/pb_public
      - ./hooks:/pb_hooks
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    labels:
      - com.centurylinklabs.watchtower.enable=false # disables Watchtower
